codigo = int (input("ingrese su codigo de estudiante: "))
nota1 = int(input("ingrese su primera nota: "))
nota2 = int( input("ingrese su segunda nota: "))
nota3 = int(input("ingrese su tercera nota: "))
print("promedio: ", ((nota1+nota2+nota3)/3), "para el estudiante: ", codigo)
